server:
  port: 8081

spring:
  application:
    name: temperature-api

logging:
  level:
    com.warmhouse: INFO
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
